In [44]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [46]:
df = pd.read_csv(r'C:\Users\syedr\OneDrive\Desktop\Personal\Skills for Data Science\Health Monitoring Project\Data\Processed.csv')

In [47]:
df

,Cholera,Rice_water_diarrhea,Vomiting,Rapid_dehydration,Abdominal_cramps,Low_grade_fever,Muscle_cramps,Typhoid,Fever_periodic,Chills_rigors,...,Fever,Tenesmus,Dehydration_symptoms,Hepatitis_A,Fever_low_grade,Anorexia_loss_of_appetite,Abdominal_pain_RUQ,Dark_urine,Pale_clay_colored_stools,Pruritus_itching
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1,1,1,0,1,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,1,1,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,1,1,1,0,1,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3995,0,0,1,0,0,0,0,0,0,0,...,0,0,0,1,1,1,1,1,1,0
3996,0,0,1,0,0,0,0,0,0,0,...,0,0,0,1,0,1,1,0,1,0
3997,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3998,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,1,0,0,1,1,0
3999,0,0,1,0,0,0,0,0,0,0,...,0,0,0,1,1,1,1,1,0,0

In [48]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4000 entries, 0 to 3999
Data columns (total 29 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Cholera                    4000 non-null   int64
 1   Rice_water_diarrhea        4000 non-null   int64
 2   Vomiting                   4000 non-null   int64
 3   Rapid_dehydration          4000 non-null   int64
 4   Abdominal_cramps           4000 non-null   int64
 5   Low_grade_fever            4000 non-null   int64
 6   Muscle_cramps              4000 non-null   int64
 7   Typhoid                    4000 non-null   int64
 8   Fever_periodic             4000 non-null   int64
 9   Chills_rigors              4000 non-null   int64
 10  Sweating                   4000 non-null   int64
 11  Headache                   4000 non-null   int64
 12  Fatigue_malaise            4000 non-null   int64
 13  Myalgia_arthralgia         4000 non-null   int64
 14  Nausea_vomiting            4000 non-null   int64
 15  Abdominal_pain             4000 non-null   int64
 16  Diarrhea                   4000 non-null   int64
 17  Loose_stools               4000 non-null   int64
 18  Nausea                     4000 non-null   int64
 19  Fever                      4000 non-null   int64
 20  Tenesmus                   4000 non-null   int64
 21  Dehydration_symptoms       4000 non-null   int64
 22  Hepatitis_A                4000 non-null   int64
 23  Fever_low_grade            4000 non-null   int64
 24  Anorexia_loss_of_appetite  4000 non-null   int64
 25  Abdominal_pain_RUQ         4000 non-null   int64
 26  Dark_urine                 4000 non-null   int64
 27  Pale_clay_colored_stools   4000 non-null   int64
 28  Pruritus_itching           4000 non-null   int64
dtypes: int64(29)
memory usage: 906.4 KB

In [49]:
df.describe()

,Cholera,Rice_water_diarrhea,Vomiting,Rapid_dehydration,Abdominal_cramps,Low_grade_fever,Muscle_cramps,Typhoid,Fever_periodic,Chills_rigors,...,Fever,Tenesmus,Dehydration_symptoms,Hepatitis_A,Fever_low_grade,Anorexia_loss_of_appetite,Abdominal_pain_RUQ,Dark_urine,Pale_clay_colored_stools,Pruritus_itching
count,4000.000000,4000.000000,4000.000000,4000.00000,4000.00000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,...,4000.000000,4000.000000,4000.00000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000
mean,0.124750,0.119500,0.240500,0.08700,0.14375,0.019500,0.040000,0.123250,0.119500,0.101750,...,0.041000,0.020000,0.05600,0.126000,0.095000,0.100250,0.074500,0.090250,0.064250,0.019000
std,0.330477,0.324416,0.427441,0.28187,0.35088,0.138291,0.195984,0.328765,0.324416,0.302357,...,0.198315,0.140018,0.22995,0.331891,0.293252,0.300371,0.262616,0.286575,0.245228,0.136542
min,0.000000,0.000000,0.000000,0.00000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.00000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.000000,0.000000,0.000000,0.00000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,0.000000,0.000000,0.000000,0.00000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,1.000000,1.000000,1.000000,1.00000,1.00000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.00000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [50]:
df = df.replace({True: 1, False: 0}).fillna(0).astype(int)

In [51]:
df

,Cholera,Rice_water_diarrhea,Vomiting,Rapid_dehydration,Abdominal_cramps,Low_grade_fever,Muscle_cramps,Typhoid,Fever_periodic,Chills_rigors,...,Fever,Tenesmus,Dehydration_symptoms,Hepatitis_A,Fever_low_grade,Anorexia_loss_of_appetite,Abdominal_pain_RUQ,Dark_urine,Pale_clay_colored_stools,Pruritus_itching
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1,1,1,0,1,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,1,1,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,1,1,1,0,1,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3995,0,0,1,0,0,0,0,0,0,0,...,0,0,0,1,1,1,1,1,1,0
3996,0,0,1,0,0,0,0,0,0,0,...,0,0,0,1,0,1,1,0,1,0
3997,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3998,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,1,0,0,1,1,0
3999,0,0,1,0,0,0,0,0,0,0,...,0,0,0,1,1,1,1,1,0,0

In [52]:
print(df.columns)

Index(['Cholera', 'Rice_water_diarrhea', 'Vomiting', 'Rapid_dehydration',
       'Abdominal_cramps', 'Low_grade_fever', 'Muscle_cramps', 'Typhoid',
       'Fever_periodic', 'Chills_rigors', 'Sweating', 'Headache',
       'Fatigue_malaise', 'Myalgia_arthralgia', 'Nausea_vomiting',
       'Abdominal_pain', 'Diarrhea', 'Loose_stools', 'Nausea', 'Fever',
       'Tenesmus', 'Dehydration_symptoms', 'Hepatitis_A', 'Fever_low_grade',
       'Anorexia_loss_of_appetite', 'Abdominal_pain_RUQ', 'Dark_urine',
       'Pale_clay_colored_stools', 'Pruritus_itching'],
      dtype='object')

In [53]:
df.to_csv(r'C:\Users\syedr\OneDrive\Desktop\Personal\Skills for Data Science\Health Monitoring Project\Data\Processed.csv', index=False)